"""MCC -> macro category rules and label attachment.

The committed artifact is data/taxonomy/mcc_to_category.csv (generated by scripts/build_taxonomy.py
from the rules below, then hand-reviewed). Ranges are the default; OVERRIDES win.
"""

from __future__ import annotations

import re
from pathlib import Path

import pandas as pd
from rapidfuzz import fuzz, process

CATEGORIES = [
    "groceries", "restaurants", "retail", "office_supplies", "software_electronics",
    "telecom_utilities", "airlines_travel", "lodging", "transport_auto_fuel", "industrial_hardware",
    "professional_services", "health", "education_gov_membership", "entertainment_media",
    "financial_postal_shipping",
]

# "we don't know" codes: excluded from headline tables, reported as their own slice
AMBIGUOUS_MCCS = {5999, 5399, 7399, 8999}

# (lo, hi, category) inclusive; first match wins after OVERRIDES
RANGES = [
    (1, 1499, "industrial_hardware"),          # agricultural services, contractors
    (1500, 2999, "industrial_hardware"),       # contractors, misc manufacturing
    (3000, 3299, "airlines_travel"),           # airline brand codes
    (3300, 3499, "transport_auto_fuel"),       # car rental brand codes
    (3500, 3999, "lodging"),                   # hotel brand codes
    (4000, 4799, "transport_auto_fuel"),       # transportation
    (4800, 4999, "telecom_utilities"),
    (5000, 5199, "industrial_hardware"),       # wholesale durable/nondurable
    (5200, 5299, "industrial_hardware"),       # home supply, lumber, hardware
    (5300, 5399, "retail"),
    (5400, 5499, "groceries"),
    (5500, 5599, "transport_auto_fuel"),       # auto dealers, service stations
    (5600, 5699, "retail"),                    # apparel
    (5700, 5799, "retail"),                    # home furnishings
    (5800, 5899, "restaurants"),
    (5900, 5999, "retail"),                    # misc retail
    (6000, 6999, "financial_postal_shipping"),
    (7000, 7099, "lodging"),
    (7200, 7299, "professional_services"),     # personal services
    (7300, 7499, "professional_services"),     # business services
    (7500, 7599, "transport_auto_fuel"),       # auto rental/repair
    (7600, 7699, "industrial_hardware"),       # repair services
    (7800, 7999, "entertainment_media"),
    (8000, 8099, "health"),
    (8100, 8199, "professional_services"),     # legal
    (8200, 8399, "education_gov_membership"),
    (8600, 8699, "education_gov_membership"),  # membership orgs
    (8700, 8999, "professional_services"),     # engineering, accounting
    (9000, 9999, "education_gov_membership"),  # government
]

OVERRIDES = {
    # office / printing
    2741: "office_supplies", 2791: "office_supplies", 5021: "office_supplies",
    5044: "office_supplies", 5111: "office_supplies", 5192: "office_supplies",
    5943: "office_supplies", 5978: "office_supplies", 7338: "office_supplies",
    # software / computers / electronics
    4816: "software_electronics", 5045: "software_electronics", 5065: "software_electronics",
    5732: "software_electronics", 5734: "software_electronics", 5815: "software_electronics",
    5816: "software_electronics", 5817: "software_electronics", 5818: "software_electronics",
    7371: "software_electronics", 7372: "software_electronics", 7375: "software_electronics",
    7379: "software_electronics",
    # telecom already 4800-4999; money transfer inside that range -> financial
    4829: "financial_postal_shipping",
    # shipping / postal / courier
    4214: "financial_postal_shipping", 4215: "financial_postal_shipping",
    4225: "financial_postal_shipping", 9402: "financial_postal_shipping",
    # travel agencies / cruise -> airlines_travel
    4411: "airlines_travel", 4511: "airlines_travel", 4582: "airlines_travel",
    4722: "airlines_travel",
    # boats / marinas -> entertainment
    4457: "entertainment_media", 4468: "entertainment_media",
    # ambulance -> health
    4119: "health",
    # fuel dealers, petroleum -> transport_auto_fuel
    5172: "transport_auto_fuel", 5983: "transport_auto_fuel", 5013: "transport_auto_fuel",
    # retail overrides inside wholesale/industrial ranges
    5094: "retail", 5137: "retail", 5139: "retail", 5300: "retail", 5309: "retail",
    5931: "retail", 5932: "retail", 5937: "retail",
    5935: "industrial_hardware", 5933: "financial_postal_shipping",
    # health inside retail range
    5047: "health", 5122: "health", 5912: "health", 5975: "health", 5976: "health",
    # entertainment / media inside retail range
    5733: "entertainment_media", 5735: "entertainment_media", 5940: "entertainment_media",
    5941: "entertainment_media", 5945: "entertainment_media", 5946: "entertainment_media",
    5970: "entertainment_media", 5971: "entertainment_media", 5994: "entertainment_media",
    # personal services that are health/entertainment
    7221: "entertainment_media", 7298: "health", 7297: "health",
    # veterinary -> professional (animal health is not human health)
    742: "professional_services",
    # lodging-range personal services -> lodging stays for 7011/7012/7032/7033 only
    # child care, charities
    8351: "education_gov_membership", 8398: "education_gov_membership",
    # education inside 8200 already; testing labs
    8734: "professional_services",
}


def categorize_mcc(mcc: int) -> tuple[str, int]:
    """Return (category, ambiguous_flag) for an MCC using OVERRIDES then RANGES."""
    if mcc in AMBIGUOUS_MCCS:
        return "AMBIGUOUS", 1
    if mcc in OVERRIDES:
        return OVERRIDES[mcc], 0
    for lo, hi, cat in RANGES:
        if lo <= mcc <= hi:
            return cat, 0
    return "AMBIGUOUS", 1


def load_mapping(taxonomy_dir: str | Path) -> pd.DataFrame:
    """Load the committed mcc_to_category.csv."""
    return pd.read_csv(Path(taxonomy_dir) / "mcc_to_category.csv", dtype={"mcc": int})


_DESC_COLS = ["edited_description", "combined_description", "usda_description", "irs_description"]


def norm_desc(s: str) -> str:
    """Uppercase, strip punctuation, collapse whitespace."""
    s = re.sub(r"[^A-Za-z0-9 ]+", " ", str(s)).upper()
    return re.sub(r"\s+", " ", s).strip()


def match_description(
    observed: str, source: pd.DataFrame, fuzzy_cutoff: int = 90
) -> tuple[int | None, str]:
    """Map an observed MCC description to an MCC via exact normalized match, then fuzzy."""
    target = norm_desc(observed)
    lookup: dict[str, int] = {}
    for col in _DESC_COLS:
        if col in source.columns:
            for mcc, d in zip(source["mcc"], source[col], strict=False):
                if isinstance(d, str) and d:
                    lookup.setdefault(norm_desc(d), int(mcc))
    if target in lookup:
        return lookup[target], "exact"
    best = process.extractOne(target, list(lookup.keys()), scorer=fuzz.token_set_ratio)
    if best and best[1] >= fuzzy_cutoff:
        return lookup[best[0]], "fuzzy"
    return None, "none"


def attach_labels(df: pd.DataFrame, taxonomy_dir: str | Path) -> pd.DataFrame:
    """Add ``mcc``, ``category``, ``ambiguous`` columns using the committed alias + mapping files.

    Rows whose description has no alias get category None and ambiguous=1 (they are excluded from
    headline tables like other ambiguous rows, and counted in the coverage table).
    """
    taxonomy_dir = Path(taxonomy_dir)
    aliases = pd.read_csv(taxonomy_dir / "mcc_description_aliases.csv", dtype={"mcc": "Int64"})
    mapping = pd.read_csv(taxonomy_dir / "mcc_to_category.csv", dtype={"mcc": int})
    alias_key = aliases.set_index(["source", "observed_description"])["mcc"]
    keys = list(zip(df["source"], df["mcc_description"], strict=False))
    mcc = pd.Series([alias_key.get(k, pd.NA) for k in keys], index=df.index, dtype="Int64")
    cat_map = mapping.set_index("mcc")["category"]
    amb_map = mapping.set_index("mcc")["ambiguous"]
    out = df.copy()
    out["mcc"] = mcc
    out["category"] = [cat_map.get(int(m)) if pd.notna(m) else None for m in mcc]
    out["ambiguous"] = [int(amb_map.get(int(m), 1)) if pd.notna(m) else 1 for m in mcc]
    return out
